//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipements()
        {
            this.Problems = new HashSet<Problems>();
        }
    
        public int EquipmentID { get; set; }
        public int UserID { get; set; }
        public string Make { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int EmployeeEmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problems> Problems { get; set; }
    }
}
