//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpdeskDbEntities : DbContext
    {
        public HelpdeskDbEntities()
            : base("name=HelpdeskDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssigneeLog> AssigneeLogs { get; set; }
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equipement> Equipements { get; set; }
        public virtual DbSet<ProblemCallLog> ProblemCallLogs { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<ProblemType> ProblemTypes { get; set; }
        public virtual DbSet<Specialist> Specialists { get; set; }
    }
}
