//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssigneeLogs> AssigneeLogs { get; set; }
        public virtual DbSet<Calls> Calls { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipements> Equipements { get; set; }
        public virtual DbSet<ProblemCallLogs> ProblemCallLogs { get; set; }
        public virtual DbSet<Problems> Problems { get; set; }
        public virtual DbSet<ProblemTypes> ProblemTypes { get; set; }
        public virtual DbSet<Specialists> Specialists { get; set; }
    }
}
