//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problems()
        {
            this.AssigneeLogs = new HashSet<AssigneeLogs>();
            this.ProblemCallLogs = new HashSet<ProblemCallLogs>();
        }
    
        public int ProblemID { get; set; }
        public string EquipementID { get; set; }
        public string EmployeeID { get; set; }
        public byte[] ProblemType { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string TimeResolved { get; set; }
        public string Solution { get; set; }
        public int ProblemTypeTypeID { get; set; }
        public int EquipementEquipmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssigneeLogs> AssigneeLogs { get; set; }
        public virtual Equipements Equipements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemCallLogs> ProblemCallLogs { get; set; }
        public virtual ProblemTypes ProblemTypes { get; set; }
    }
}
