//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemCallLog
    {
        public int CallID { get; set; }
        public string ProblemID { get; set; }
        public int ProblemProblemID { get; set; }
        public int CallCallID { get; set; }
    
        public virtual Call Call { get; set; }
        public virtual Problem Problem { get; set; }
    }
}
