//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int SpecialistID { get; set; }
        public int NumberOfProblems { get; set; }
        public string Speciality { get; set; }
        public int Employee_EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
